### ISSUE TITLE
Interrupt serial

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#13]
Interrupt branch: Arduino_Animal_Tag/interrupts/interrupts.ino 
Why are we running the serial at 38400 and not 9600, like we've been using on the rest of the project?

**Comment by TheBen27** [comment]
This was an artifact of some testing i was doing. I expected that Serial
could not finish transmitting data before another interrupt happened. This
turned out to be true... since the accelerometer was running at 800Hz
instead of 25.

In any case, this was just a test sketch.  A baud rate of 9600 will still
be used for the final code.

--Ben
