### ISSUE TITLE
Code with only SD writes

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#23]
Similar to issue #22, but the opposite. I want a little code that does a lot of SD writing for power testing reasons.

**Comment by TheBen27** [comment]
In other words, you want code that just constantly writes data to the SD
card?
Slightly more difficult than the last one, but not by much.

On Mar 13, 2017 3:49 PM, "William Laney" <notifications@github.com> wrote:

Similar to issue #22
<https://github.com/WLaney/Arduino_Animal_Tag/issues/22>, but the opposite.
I want a little code that does a lot of SD writing for power testing
reasons.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/WLaney/Arduino_Animal_Tag/issues/23>, or mute the thread

**Comment by WLaney** [comment]
That's right. If it's hard or will take a while don't worry about it. This is not super important.

**Comment by TheBen27** [comment]
Alright. In `miscellaneous sketches/sd_stress_test`, you will find the abomination you are looking for.
It just pushes garbage data to the SD as fast as it can.

**Comment by WLaney** [comment]
Thank you Ben, you're the hero that we need
