### ISSUE TITLE
Tag resets on SD card insert

### ISSUE THREAD

**Issue by TheBen27** [WLaney/Arduino_Animal_Tag#26]
Hey, guys.

As you know, I don't really know electronics, so "power fluctuation" is a bit of an embellishment on my part. Regardless, when I insert an SD card into my Sharkduino, the power light flickers. It also seems to disconnect and reconnect the device - I sometimes have to switch the port in the Arduino IDE (between /dev/ttyUSB0 and /dev/ttyUSB1).

I don't know for how long this has been occurring, but I just noticed it earlier today.

Is this something we should worry about? Could this be related to our old problem with the device resetting while recording data?

Thanks.
--Ben

**Comment by WLaney** [comment]
Isn't your sharkduino the one where the gyro doesn't work? If so it's already broken and I don't know what the under lying cause of the problem is. The issue could be manifesting in diffrent ways. You should stop using it, and grab V2.1b from small.

I'll look at yours and some of the other Sharkduinos to see if I can figure out what is going on.

**Comment by TheBen27** [comment]
Fair enough. I'll pick it up tomorrow.
For now, I guess we can consider this case closed.
